const productsActionsTypes = {
  FETCH_ALL_PRODUCTS_REQUEST: 'FETCH_ALL_PRODUCTS_REQUEST',
  FETCH_ALL_PRODUCTS_FAILED: 'FETCH_ALL_PRODUCTS_FAILED',
  FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',

  SET_CURRENT_FILTERED_PRODUCTS: 'SET_CURRENT_FILTERED_PRODUCTS',
}

export default productsActionsTypes
