const productActionsTypes = {
  FETCH_ALL_PRODUCTS_REQUEST: 'FETCH_ALL_PRODUCTS_REQUEST',
  FETCH_ALL_PRODUCTS_FAILED: 'FETCH_ALL_PRODUCTS_FAILED',
  FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
}

export default productActionsTypes
